### ISSUE TITLE
SBP read count datasets

### ISSUE THREAD

**Issue by lynngao** [wdl2459/ConQuR#12]
Hi,
Thank you for the release. I am doing a research of comparing different normalization methods in terms of downstream machine learning model prediction performance, and I would like to use the count datasets with SBP as trait. I tried with the sample data in this repo, but ConQuR results are not that significant and we suspected that is caused by the sample data doesn't have too much batch effects from the PCoA plots. I wonder is there any way to get the complete 6 read count datasets? Thank you so much!

**Comment by wdl2459** [comment]
Thanks for the question. Since we are not allowed to disclose the CARDIA data, we added noise to a subset of the dataset and made it the sample data in the package. To obtain the full data, which currently has 7 batches (maybe even more), please submit a request due to the CARDIA Study Publications Policy. A request can be made by submitting a CARDIA Data Set Request-Intent to Analyze Form to the CARDIA Coordinating Center, University of Alabama at Birmingham, at https://www.cardia.dopm.uab.edu/publications-2/publications-documents.
